services:
  git:
    image: charmcli/soft-serve:latest
    container_name: soft-serve
    volumes:
      # - ./data:/soft-serve
      - /srv/soft-serve:/soft-serve
      - /etc/localtime:/etc/localtime
    ports:
      - 23231:23231
      - 23232:23232
      - 23233:23233
      - 9418:9418
    restart: always
    # environment:
    #   SOFT_SERVE_INITIAL_ADMIN_KEYS:
    labels:
      com.centurylinklabs.watchtower.enable: true
networks:
  default:
    name: git
