services:
  beszel:
    image: henrygd/beszel:latest
    container_name: beszel
    restart: unless-stopped
    # ports:
    #   - 8090:8090
    networks:
      - tsdproxy
    volumes:
      - ${BESZEL_DATA_DIR}:/beszel_data
      - ./beszel_socket:/beszel_socket
    labels:
      tsdproxy.enable: "true"
      tsdproxy.name: "beszel"
      com.centurylinklabs.watchtower.enable: true

  beszel-agent:
    image: henrygd/beszel-agent:latest
    container_name: beszel-agent
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./beszel_socket:/beszel_socket
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      LISTEN: /beszel_socket/beszel.sock
      KEY: '${BESZEL_KEY}' # Do not remove quotes around the key
    depends_on:
      - beszel
    labels:
      com.centurylinklabs.watchtower.enable: true

networks:
  default:
    name: monitoring

  tsdproxy:
    name: tsdproxy
    external: true
