name: backrest

services:
  backrest:
    image: ghcr.io/garethgeorge/backrest:latest
    container_name: backrest
    hostname: backrest
    restart: always
    volumes:
      - ${DATA_DIR}/data:/data
      - ${DATA_DIR}/config:/config
      - ${DATA_DIR}/cache:/cache
      - ${DATA_DIR}/tmp:/tmp
      # - ${DATA_DIR}/rclone:/root/.config/rclone # Mount for rclone config (needed when using rclone remotes)
      # - /path/to/backup/data:/userdata  # Mount local paths to backup
      # - /path/to/local/repos:/repos     # Mount local repos (optional for remote storage)
    environment:
      - BACKREST_DATA=/data
      - BACKREST_CONFIG=/config/config.json
      - XDG_CACHE_HOME=/cache
      - TMPDIR=/tmp
    ports:
      - "9898:9898"
