services:
  copyparty:
    container_name: copyparty
    image: ghcr.io/9001/copyparty-ac:latest
    user: "1000:1000"
    restart: on-failure
    ports:
      - 3923:3923
    volumes:
      - ./copyparty.conf:/cfg/copyparty.conf
      - /mnt/copyparty:/data
