services:
  dockge:
    image: louislam/dockge:1
    container_name: dockge
    restart: unless-stopped
    ports:
      - 5001:5001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /srv/dockge:/app/data
      # If you want to use private registries, you need to share the auth file with Dockge:
      # - /root/.docker/:/root/.docker

      # Stacks Directory
      # ⚠️ READ IT CAREFULLY. If you did it wrong, your data could end up writing into a WRONG PATH.
      # ⚠️ 1. FULL path only. No relative path (MUST)
      # ⚠️ 2. Left Stacks Path === Right Stacks Path (MUST)
      # - /opt/stacks:/opt/stacks
      - /home/yuki/homelab:/opt/stacks
    environment:
      # Tell Dockge where is your stacks directory
      DOCKGE_STACKS_DIR: /opt/stacks
      DOCKGE_ENABLE_CONSOLE: true
    networks:
      - tsdproxy
    labels:
      tsdproxy.enable: "true"
      tsdproxy.name: "dockge"
      com.centurylinklabs.watchtower.enable: true

networks:
  default:
    name: dockge
  tsdproxy:
    name: tsdproxy
    external: true
